// export { assertEquals } from 'https://deno.land/std@0.210.0/assert/mod.ts'
// import DatasetCore from 'https://esm.sh/@rdfjs/dataset@2.0.1/DatasetCore.js'
// export type { Quad, NamedNode, Term, Literal } from 'https://esm.sh/@rdfjs/types@1.1.0'
// import dataFactory from 'https://esm.sh/@rdfjs/data-model@2.0.1'
// import namespace from 'https://esm.sh/@rdfjs/namespace@2.0.0'
// export { Parser, Store, Writer, DataFactory } from 'https://esm.sh/n3@1.17.2'
// export type { WriterOptions } from 'https://esm.sh/n3@1.17.2'
// import ProgressBar from 'https://deno.land/x/progressbar@v0.2.0/progressbar.ts'
// import { Validator } from 'https://esm.sh/shacl-engine@0.1.1'
// export { walk } from 'https://deno.land/std@0.210.0/fs/walk.ts'
// export { percentageWidget, amountWidget } from 'https://deno.land/x/progressbar@v0.2.0/widgets.ts'
// export { DatasetCore, dataFactory, namespace, ProgressBar, Validator as ShaclValidator }

// export { assertEquals } from 'https://deno.land/std@0.210.0/assert/mod.ts'
import DatasetCore from '@rdfjs/dataset'
export type { Literal, NamedNode, Quad, Term } from '@rdfjs/types'
import dataFactory from '@rdfjs/data-model'
import namespace from '@rdfjs/namespace'
export type { WriterOptions } from 'n3'
export { DataFactory, Parser, Store, Writer } from 'n3'
// import ProgressBar from 'https://deno.land/x/progressbar@v0.2.0/progressbar.ts'
import { Validator } from 'shacl-engine'
// export { walk } from 'https://deno.land/std@0.210.0/fs/walk.ts'
// export { percentageWidget, amountWidget } from 'https://deno.land/x/progressbar@v0.2.0/widgets.ts'
export { dataFactory, DatasetCore, namespace, Validator as ShaclValidator }
